name: Lint and Test

on:
  push:
    branches: [ main ] # Running on every branch causes double runs for PR commits
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Xcode Select
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'

      - name: Cache Swift Build
        uses: actions/cache@v3
        with:
          path: .build
          key: swift-build-cache

      # Runs a single command using the runners shell
      - name: Build
        run: swift build

  test:
    runs-on: macos-12
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Xcode Select
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'

      - name: Cache Swift Build
        uses: actions/cache@v3
        with:
          path: .build
          key: swift-build-cache # -${{ hashFiles('**/*.swift') }}

      - name: Test
        run: swift test

  lint:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v1

      # Don't need submodules for linting
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
